---
- hosts: jenkins
  become: yes
  tasks:
 
    - name: install jdk8
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: download maven
      get_url: url=http://mirrors.estointernet.in/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz dest=/opt/apache-maven-3.6.1-bin.tar.gz
    
    - name: extract maven
      command: tar -xvf /opt/apache-maven-3.6.1-bin.tar.gz -C /opt
    
#    - name: change the name
#      command: mv /opt/apache-maven-3.6.1 /opt/maven
  
    - name: export the maven path
      shell: echo 'export MAVEN_HOME=/opt/maven'>> /etc/profile
    
    - name: export the maven path
      shell: echo 'export PATH=$PATH:$MAVEN_HOME/bin'>> /etc/profile

    - name: update the profile
      shell: source /etc/profile
     
    - name: set env_JDK
      shell: echo 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64'>>/etc/profile
    - name: setup in userprofile
      shell: echo 'export PATH=$PATH:$JAVA_HOME/bin'>> /etc/profile
    - name: update the env variables in profile
      shell: source /etc/profile

    - name: install jenkins repo
      shell:  sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo

    - name: download the repo key
      shell: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Download the jenkins
      shell:  yum install jenkins -y
        

    - name: start the jenkins server
      service: name=jenkins state=restarted
