- hosts: slave
  become: yes
  tasks:
   - name: installing package
     package: 
      name: httpd
      state: present
   - service: 
      name: httpd
      state: started



   - name: install jdk8
     yum:
      name: java-1.8.0-openjdk
      state: present
 #  - name: set env_JDK
 #   shell: echo 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64'>>/etc/profile
 #  - name: setup in userprofile
 #    shell: echo 'export PATH=$PATH:$JAVA_HOME/bin'>> /etc/profile
 #  - name: update the env variables in profile
 #    shell: source /etc/profile





#   - name: install apache-tomcat
#     get_url:
#      url: http://mirrors.estointernet.in/apache/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz 
#      dest: /opt/
#   - name: untar file
#     command: tar xvf apache-tomcat-7.0.94.tar.gz

- hosts: all
  become: yes
  tasks:
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
       src: http://mirrors.estointernet.in/apache/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz
       dest: /opt/
       remote_src: yes

    - name: Change Ownership and group of the Tomcat directory
      file: path=/opt/tomcat7 owner=ansible group=ansible mode=775 state=directory recurse=yes
    - name: restart tomcat
      command: nohup /opt/tomcat7/bin/startup.sh # Execute command even after you have exited from the shell prompt
      become: true
      become_user: ansible 

- hosts: jenkins
  become: yes
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-x64.rpm
  tasks:
    - name: Download JDK 8 RPM file
      command: "wget --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}}"              
    - name: install JDK 8
      command: "rpm -ivh jdk-8u171-linux-x64.rpm"
